# Generated by Django 5.1.5 on 2026-08-27 18:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('capacity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('seats_taken', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['starts_at', 'id'],
                'indexes': [models.Index(fields=['is_active', 'starts_at'], name='session_active_starts_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('seats_taken__lte', models.F('capacity'))), name='seats_within_capacity'), models.CheckConstraint(condition=models.Q(('capacity__gte', 1)), name='capacity_min_1')],
            },
        ),
    ]
